[project]
name = "stock-trade-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.3",
    "mplfinance>=0.12.10b0",
    "nbstripout>=0.8.1",
    "yfinance>=0.2.62",
]
